#versão do linux
os: linux
dist: focal

#linguagem utilizada para desenvolver a app
language: python

#versao q a app suporte
python:
  - "3.8"

addons:
  sonarcloud:
    organization: developerarthur
    token: ${SONAR_TOKEN}

#instalacao de modulos necessarios para a app
install:
  - pip install flask pytest flask-wtf coverage

script:
  - coverage run -m pytest test.py || travis_terminate 1;
  - coverage report app.py || travis_terminate 1;
  - coverage xml app.py || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true
  app: devsecops-sre
  on:
      branch: main